### PR TITLE
Lacuna generative logo

### PR DESCRIPTION
**Pull request by action-script**

### CODE REVIEW

**Comment by mrzl** [comment]
did anybody check this out already? is there any special setup?

**Comment by action-script** [comment]
There is not special setup.
The main change is on the front end, the code runs without modify nothing else than the main page logo, just if there is available creative code on the server and the browser supports canvas and WebGL.

**Comment by mrzl** [comment]
It's a bit weird, I just checked it out but couldn't get it to work.

When I compile this, there is no random_url set here when I run it: https://github.com/LacunaLab/lacunalab-website/blob/LACUNA-generative_logo/js/logo.js#L43-L45 even `window.generative_logo_sketches.length` is 0

while i have two sketches in this directory:

    generative_logo/example/main.example.js
    generative_logo/example1/main.js

for some reason none of these .js files is being detected by that script. or is there anything i am missing?

**Comment by action-script** [comment]
@mrzl 
The script includes all the main.js files that are under the 'generative_logo' directory.
The example is not being included. So if yon run the project without any generative logo sketch or just with the example one, the 'window.generative_logo_sketches' array will be empty and no p5 logo is gonna be rendered.

Now, you said you tried with:
_generative_logo/example1/main.js_
Then I have to check this, because that should works. Gonna take a look on it :)

**Comment by hiroMTB** [comment]
Any news?

**Comment by mrzl** [comment]
Just try to run it.. i couldn't.. Maybe this can go to 🗑

**Comment by hiroMTB** [comment]
@action-script ?

**Pull request closed without merging**
